spring:
  session:
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:mariadb://sorma.asuscomm.com:3307/malldb?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: june
    password: crain008*
    driver-class-name: org.mariadb.jdbc.Driver