spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  #    open-in-view: false
  #    defer-datasource-initialization: true
  #    generate-ddl: true

  # 파일 업로드
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security.web: trace
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

com:
  june:
    upload:
      path: upload